name: "Automated Release"
description: "Promotes Staging to Production, Creates GitHub Release"
inputs:
  github-token:
    description: "github token"
    required: true
  action-type:
    description: "promote or release"
    required: true
  heroku-api-key:
    description: "Heroku API Key"
    required: true
  pipeline-id:
    description: "Heroku Pipline ID"
  source-app-id:
    description: "Heroku Source APP ID"
  target-app-id:
    description: "Heroku Target APP ID"
outputs:
  release-title:
    description: "Release title"
  release-tag:
    description: "Release tag"
  release-body:
    description: "Release summary notes"
  promote-status:
    description: "Heroku Promote Status"
runs:
  using: "node12"
  main: "index.js"
