name: "Automated Release"
description: "Promotes Staging to Production or/and Creates GitHub Release"
inputs:
  github-token:
    description: "github token"
    required: true
  action-type:
    description: "promote or release or source-release-status or target-release-status"
    required: true
  heroku-api-key:
    description: "Heroku API Key"
    required: true
  pipeline-id:
    description: "Heroku Pipline ID"
    required: true
  source-app-id:
    description: "Heroku Source APP ID"
    required: true
  target-app-id:
    description: "Heroku Target APP ID"
    required: true
  clubhouse-token:
    description: "clubhouse token"
    required: true
  clubhouse-story-ids:
    description: "clubhouse story ids to update"
    required: true
outputs:
  release-title:
    description: "Release title"
  release-tag:
    description: "Release tag"
  release-body:
    description: "Release summary notes"
  promote-status:
    description: "Heroku Promote Status"
  source-app-status:
    description: "Heroku Source Last Release Status"
  target-app-status:
    description: "Heroku Target Last Release Status"
  clubhouse-story-ids:
    description: "An array of Clubhouse Stories to update"
  message:
    description: "Extra Messages"
runs:
  using: "node12"
  main: "index.js"
