name: "Hello World"
description: "Greet someone and record the time"
inputs:
  github-token:
    description: "github token"
    required: true
  action-type:
    description: "promote or release"
    required: true
  heroku-api-key:
    description: "Heroku API Key"
    required: true
  heroku-email:
    description: "Heroku Email"
    required: true
  heroku-app-name:
    description: "Heroku App Name"
    default: "rotabull-staging"
  pipeline-id:
    description: "Heroku Pipline ID"
  source-app-id:
    description: "Heroku Source APP ID"
  target-app-id:
    description: "Heroku Target APP ID"
outputs:
  release-title:
    description: "Release title"
  release-tag:
    description: "Release tag"
  release-body:
    description: "Release summary notes"
  promote-status:
    description: "Heroku Promote Status"
  slack-message:
    description: "Slack Block Kit Payload"
runs:
  using: "node12"
  main: "index.js"
